# Generated by Django 5.1 on 2024-11-05 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=240)),
                ('contact', models.CharField(max_length=16)),
                ('proced', models.CharField(choices=[('CH', 'sobrancelhas com henna'), ('SH', 'sobrancelhas sem henna'), ('MH', 'Micro henna'), ('LP', 'Limpeza de pele'), ('SL', 'SPA labial'), ('DE', 'Depilação Buço e Axila'), ('LA', 'Laminação dos fios'), ('PE', 'Peeling facial superficial'), ('ES', 'Estriderme'), ('NF', 'Nano fios'), ('RE', 'Revitalização facial'), ('DF', 'Default')], default='DF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='modelPerfume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('adress', models.TextField()),
            ],
        ),
    ]
