# Generated by Django 5.1 on 2024-08-19 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('data', models.DateField()),
                ('time', models.TimeField()),
                ('email', models.EmailField(max_length=240)),
                ('contact', models.CharField(max_length=16)),
            ],
        ),
    ]
