# Generated by Django 5.1 on 2024-11-06 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='modelperfume',
            name='adress',
        ),
        migrations.AddField(
            model_name='modelperfume',
            name='aroma',
            field=models.CharField(choices=[('F', 'Floral'), ('C', 'Citrico'), ('AM', 'Amadeirado'), ('AD', 'Adocidado'), ('D', 'Default')], default='D', max_length=2),
        ),
        migrations.AddField(
            model_name='modelperfume',
            name='numberContact',
            field=models.CharField(default='000000000', max_length=16),
        ),
        migrations.AddField(
            model_name='modelperfume',
            name='product',
            field=models.CharField(choices=[('P', 'Perfume'), ('H', 'Hidratante'), ('A', 'Antioxidante'), ('D', 'Default')], default='D', max_length=1),
        ),
        migrations.AddField(
            model_name='modelperfume',
            name='quant',
            field=models.CharField(choices=[('0', '0 ml'), ('1', '10 ml'), ('3', '30 ml'), ('5', '50 ml')], default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='cadastro',
            name='proced',
            field=models.CharField(choices=[('CH', 'sobrancelhas COM henna'), ('SH', 'sobrancelhas SEM henna'), ('MH', 'Micro Henna'), ('LP', 'Limpeza de Pele'), ('SL', 'SPA Labial'), ('DE', 'Depilação Buço e Axila'), ('LA', 'Laminação dos fios'), ('PE', 'Peeling facial superficial'), ('ES', 'Estriderme'), ('NF', 'Nano Fios'), ('RE', 'Revitalização Facial'), ('DF', 'Default')], default='DF', max_length=2),
        ),
    ]
