# Generated by Django 5.1 on 2024-09-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_modelperfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('op1', 'Opcao 1'), ('op2', 'Opcao 2'), ('op3', 'Opcao 3'), ('op4', 'Opcao 4'), ('op5', 'Opcao 5')], default='op1', max_length=4)),
            ],
        ),
    ]
