# Generated by Django 5.1 on 2024-11-19 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_remove_modelperfume_adress_modelperfume_aroma_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelperfume',
            name='quant',
            field=models.CharField(choices=[('1', '10 ml'), ('3', '30 ml'), ('5', '50 ml'), ('10', '100 ml'), ('0', '0 ml')], default='0', max_length=2),
        ),
    ]
