# Generated by Django 5.1 on 2024-09-14 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_modelperfume'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(choices=[('perfume', 'Perfume'), ('hidratante', 'Hidratante'), ('peelins', 'Peelins'), ('antioxidante', 'Antioxidante'), ('outro', 'Outro')], max_length=100)),
                ('category', models.CharField(choices=[('floral', 'Floral'), ('citrico', 'Citrico'), ('amadeirado', 'Amadeirado'), ('outro1', 'Outro1')], max_length=100)),
            ],
        ),
    ]
