# Generated by Django 5.1 on 2024-11-25 19:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_modelperfume_quant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cadastro',
            old_name='time',
            new_name='horario',
        ),
    ]
