# Generated by Django 5.1 on 2024-12-17 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_time_cadastro_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='modelIndisponivel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField()),
                ('horarioInicio', models.TimeField()),
                ('horarioFim', models.TimeField()),
            ],
        ),
    ]
