# Generated by Django 5.1 on 2024-12-31 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_rename_time_cadastro_horario'),
    ]

    operations = [
        migrations.AddField(
            model_name='cadastro',
            name='horarioFim',
            field=models.TimeField(default='13:30'),
        ),
    ]
