# Generated by Django 5.1 on 2024-12-31 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0005_cadastro_horariofim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cadastro',
            name='horarioFim',
        ),
    ]
